apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "projectsveltos.fullname" . }}-addon-constraint-metrics-reader
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get