apiVersion: v1
kind: Service
metadata:
  name: addon-controller-metrics-service
  labels:
    control-plane: addon-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.addonControllerMetricsService.type }}
  selector:
    control-plane: addon-controller
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.addonControllerMetricsService.ports | toYaml | nindent 2 -}}