apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectsveltos.fullname" . }}-classifier-manager-metrics-service
  labels:
    control-plane: classifier
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.classifierManagerMetricsService.type }}
  selector:
    control-plane: classifier
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.classifierManagerMetricsService.ports | toYaml | nindent 2 -}}