apiVersion: v1
kind: Service
metadata:
  name: event-manager-metrics-service
  labels:
    control-plane: event-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.eventManagerMetricsService.type }}
  selector:
    control-plane: event-manager
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.eventManagerMetricsService.ports | toYaml | nindent 2 -}}