apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectsveltos.fullname" . }}-fm-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fmManagerMetricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.fmManagerMetricsService.ports | toYaml | nindent 2 -}}