apiVersion: v1
kind: Service
metadata:
  name: hc-manager-metrics-service
  labels:
    control-plane: hc-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hcManagerMetricsService.type }}
  selector:
    control-plane: hc-manager
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.hcManagerMetricsService.ports | toYaml | nindent 2 -}}