apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectsveltos.fullname" . }}-sc-manager-metrics-service
  labels:
    control-plane: sc-manager
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scManagerMetricsService.type }}
  selector:
    control-plane: sc-manager
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.scManagerMetricsService.ports | toYaml | nindent 2 -}}