apiVersion: v1
kind: Service
metadata:
  name: shard-controller-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: shard-controller
    app.kubernetes.io/part-of: shard-controller
    control-plane: shard-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.shardControllerMetricsService.type }}
  selector:
    control-plane: shard-controller
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.shardControllerMetricsService.ports | toYaml | nindent 2 -}}