apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shard-metrics-reader
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: shard-controller
    app.kubernetes.io/part-of: shard-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get