apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectsveltos.fullname" . }}-sveltosctl
  labels:
    app: sveltosctl
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sveltosctl.type }}
  selector:
    app.kubernetes.io/name: sveltosctl
  {{- include "projectsveltos.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.sveltosctl.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "projectsveltos.fullname" . }}-sveltosctl
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sveltosctl
  serviceName: sveltosctl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sveltosctl
    spec:
      containers:
      - args:
        - snapshot
        - reconciler
        - v=5
        command:
        - /sveltosctl
        image: projectsveltos/sveltosctl-amd64:v0.9.0
        imagePullPolicy: IfNotPresent
        name: sveltosctl
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /collection
          name: collection
        - mountPath: /etc/localtime
          name: tz-config
        - mountPath: /tmp
          name: tmp
      serviceAccountName: sveltosctl
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /usr/share/zoneinfo/America/Los_Angeles
        name: tz-config
  volumeClaimTemplates:
  - metadata:
      name: collection
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard