apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "projectsveltos.fullname" . }}-sveltosctl
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - namespaces
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterconfigurations
  - clusterreports
  verbs:
  - get
  - list
- apiGroups:
  - config.projectsveltos.io
  resources:
  - clusterprofiles
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - classifiers
  - eventsources
  - healthchecks
  - eventbasedaddons
  verbs:
  - get
  - list
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - sveltosclusters
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - utils.projectsveltos.io
  resources:
  - snapshots
  - techsupports
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - utils.projectsveltos.io
  resources:
  - snapshots/finalizers
  - techsupports/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - utils.projectsveltos.io
  resources:
  - snapshots/status
  - techsupports/status
  verbs:
  - '*'
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - rolerequests
  - rolerequests/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "projectsveltos.fullname" . }}-sveltosctl
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "projectsveltos.fullname" . }}-sveltosctl'
subjects:
- kind: ServiceAccount
  name: '{{ include "projectsveltos.fullname" . }}-sveltosctl'
  namespace: '{{ .Release.Namespace }}'